---
# confgig general de tout les hosts

- name: Installation de collectd-core
  package: name=collectd-core state=present default_release=jessie-backports

- name: Installation de liboping0
  package: name=liboping0 state=present

- name: Créer repertoire collectd
  file: path=/etc/collectd/collectd.conf.d/ state=directory owner=root group=root mode="u+rwX,g+rwX,o+r" recurse=yes

- name: Copie des fichier de configuration
  copy: src={{ item }} dest=/etc/collectd/{{ item }} owner=root group=root mode="u+rw,g+r,o+r"
  with_items:
    - collectd.conf
    - collectd.conf.d/cpu.conf
    - collectd.conf.d/df.conf
    - collectd.conf.d/entropy.conf
    - collectd.conf.d/load.conf
    - collectd.conf.d/memory.conf
    - collectd.conf.d/swap.conf
    - collectd.conf.d/syslog.conf
    - collectd.conf.d/uptime.conf
    - collectd.conf.d/users.conf
    - collectd.conf.d/interface.conf

- name: Copie des fichier de configuration
  copy: src={{ item }} dest=/etc/collectd/{{ item }} owner=root group=root mode="u+rw,g+r,o+r"
  with_items:
    - collectd.conf.d/ping.conf
    - collectd.conf.d/conntrack.conf

  when: ansible_hostname not in sshprotect_disable

- name: collectd config
  replace: dest=/etc/collectd/collectd.conf regexp='^#Hostname "localhost"$' replace='Hostname "{{ inventory_hostname }}"' backup=no

- name: Copie des fichier de configuration collectd network
  template: src=network.j2 dest=/etc/collectd/collectd.conf.d/network.conf owner=root group=root mode="u+rw,g+r,o+r"

- name: Activer le service collectd au démérage
  service: name=collectd state=restarted enabled=yes
