---

- name: Installation de postfix
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - postfix
    - postfix-mysql
    - clamav-milter
    - clamav-unofficial-sigs
    - spamass-milter
    - spamassassin
    - milter-greylist
    - opendkim
    - opendkim-tools

- name: Ajout de l'user vmail
  user: name=vmail shell=/bin/false append=yes state=present uid=5000 home=/var/mail

- name: Ajout de l'user spamd
  user: name=spamd shell=/bin/false append=yes state=present uid=5001 home=/var/lib/spamassassin

- name: Copie des fichier de configuration postfix
  copy: src={{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode="u+r,g-rwx,o-rwx"
  with_items:
    - main.cf
    - master.cf
    - smtp_header_checks
    - mailing-virtual
  notify:
    - restart postfix

- name: postmap mailing
  command: postmap /etc/postfix/mailing-virtual

- name: Copie des fichier de configuration postfix
  copy: src=secured/dh4096.pem dest=/etc/postfix/dh4096.pem owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart postfix

- name: Copie du fichier postfix
  template: src={{ item }}.j2 dest=/etc/postfix/{{ item }} owner=root group=dovecot mode="u+rw,g+r,o+r"
  with_items:
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-email2email.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
  notify:
    - restart postfix

- name: config clamav-milter
  copy: src=clamav-milter.conf dest=/etc/clamav/clamav-milter.conf owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart clamav-milter

- name: config spamass-milter
  replace: dest=/etc/default/spamass-milter regexp='^OPTIONS="(.)*' replace='OPTIONS="-u spamass-milter -i 127.0.0.1 -m -r -1 -I"' backup=no
  notify:
    - restart spamass-milter

- name: config spamassassin
  copy: src=spamassassin  dest=/etc/default/spamassassin owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart spamassassin

- name: config milter-greylist
  copy: src=greylist.conf  dest=/etc/milter-greylist/greylist.conf owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart milter-greylist

- name: config opendkim
  copy: src=opendkim.conf  dest=/etc/opendkim.conf owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart opendkim

- name: Créer repertoire opendkim
  file: path=/etc/opendkim/key state=directory owner=root group=root mode="u+rwX,g+rwX,o+r" recurse=yes

- name: Activer postfix au démérage
  service: name=postfix state=started enabled=yes

- name: Activer clamav-milter au démérage
  service: name=clamav-milter state=started enabled=yes

- name: Activer spamass-milter au démérage
  service: name=spamass-milter state=started enabled=yes

- name: Activer spamassassin au démérage
  service: name=spamassassin state=started enabled=yes

- name: Activer milter-greylist au démérage
  service: name=milter-greylist state=started enabled=yes

- name: Activer opendkim au démérage
  service: name=opendkim state=started enabled=yes
