---

- name: Installation de postfix
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - postfix
    - postfix-mysql
    - rspamd
    - rmilter
    - redis-server
    - clamav-unofficial-sigs

- name: Ajout de l'user vmail
  user: name=vmail shell=/bin/false append=yes state=present uid=5000 home=/var/mail

- name: Copie des fichier de configuration postfix
  copy: src={{ item }} dest=/etc/postfix/{{ item }} owner=root group=root mode="u+r,g-rwx,o-rwx"
  with_items:
    - main.cf
    - master.cf
    - smtp_header_checks
  notify:
    - restart postfix

- name: Copie du fichier postfix
  template: src={{ item }}.j2 dest=/etc/postfix/{{ item }} owner=root group=dovecot mode="u+rw,g+r,o+r"
  with_items:
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-email2email.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
  notify:
    - restart postfix

- name: Activer postfix au démérage
  service: name=postfix state=started enabled=yes
