---

- name: Installation de sensu-client
  apt: name=sensu state=present cache_valid_time=3600

- name: Copie des fichier de configuration monit
  copy: src={{ item }} dest=/etc/{{ item }} owner=root group=root mode="u+r,g-rwx,o-rwx"

- name: Activer monit au démérage
  service: name=sensu-client state=started enabled=yes

