---

- name: Installation de sensu
  apt: name=sensu state=present cache_valid_time=3600

- name: Installation des depence
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - bc


- name: Copie des fichier de config server
  copy: src=config.json dest=/etc/sensu/config.json owner=root group=root mode="u+rw,g+r,o+r"
  when: ansible_fqdn != "c-3po.tharyrok.eu.org"

- name: Copie des fichier de sensu client
  template: src=sensu.j2 dest=/etc/sensu/conf.d/client.json owner=root group=root mode="u+rw,g+r,o+r"

- name: Activer le service sensu au démérage
  service: name=sensu-client state=restarted enabled=yes

- name: Download tharyrok-sensu-plugins
  git: repo=https://github.com/Tharyrok/sensu-plugins-shell dest=/opt/tharyrok-sensu-plugins

- name: Enable check-cpu.sh
  sensu_check: name=check-cpu command="/opt/tharyrok-sensu-plugins/check-cpu.sh" subscribers=default interval=60

- name: Enable check-cpu.sh
  sensu_check: name=check-memory-percent command="/opt/tharyrok-sensu-plugins/check-memory-percent.sh" subscribers=default interval=60
