---
# ajout des users & leurs cles ssh

- name: Update root
  user: name=root shell=/bin/zsh state=present

- name: Ajout des utilisateurs
  user: name={{ item.name }} shell=/bin/zsh groups=sudo append=yes state=present
  with_items: "{{ users }}"

- name: Ajout cles ssh aux utilisateurs
  authorized_key: user={{ item.0.name }} key="{{ item.1 }}"
  with_subelements:
     - "{{ users }}"
     - keys
