---
# confgig general de tout les hosts

- name: Installation de nginx
  apt: name={{ item }} state=present
  with_items:
    - nginx-full
    - liblwp-useragent-determined-perl
    - unzip

- name: Créer repertoire default et erreur
  file: path=/var/www/{{ item }} state=directory owner=www-data group=www-data mode="u+rwX,g+rwX,o+r" recurse=yes
  with_items:
    - error
    - default

- name: Créer repertoire ssl nginx
  file: path=/etc/nginx/ssl state=directory owner=www-data group=www-data mode="u+rwX,g+rwX,o+r" recurse=yes

- name: Copie des fichier de nginx
  copy: src={{ item }} dest=/etc/nginx/{{ item }} owner=root group=root mode="u+rw,g+r,o+r"
  with_items:
    - nginx.conf
    - sites-available/default
    - ssl/nginx.crt
    - ssl/nginx.key

- name: Création fihier conf.d/stopforumspam.conf
  file: path=/etc/nginx/conf.d/stopforumspam.conf state=touch mode="u+rw,g+r,o+r"

- name: Copie default site et error
  copy: src=web/{{ item }} dest=/var/www/{{ item }} owner=www-data group=www-data mode="u+rw,g+r,o+r"
  with_items:
    - default/index.html
    - error/-error-404.html
    - error/-error-50x.html

- name: téléchargement plugin munin
  get_url: url=https://raw.githubusercontent.com/perusio/nginx-munin/master/{{ item }} dest=/usr/share/munin/plugins/{{ item }} mode="u+rwx,g+rx,o+rx" force=yes
  with_items:
    - nginx_connection_request
    - nginx_memory
    - nginx_request
    - nginx_status

- name: Lien symbolique munin
  file: src=/usr/share/munin/plugins/{{ item }} dest=/etc/munin/plugins/{{ item }} owner=munin group=munin state=link
  with_items:
    - nginx_connection_request
    - nginx_memory
    - nginx_request
    - nginx_status

- name: Copie des fichier de nginx pour munin
  copy: src=munin dest=/etc/munin/plugin-conf.d/nginx owner=munin group=munin mode="u+rw,g+r,o+r"

- name: Création reprtoir pour le script de ban
  file: path=/opt/tharyrok/stopforumspam state=directory owner=root group=root mode="u+rwX,g+rwX,o+r" recurse=yes
  when: ansible_hostname in spam_nginx

- name: Copie des fichier de nginx pour munin
  copy: src=spam.sh dest=/opt/tharyrok/stopforumspam/spam.sh owner=root group=root mode="u+rwx,g+rx,o+rx"

- name: Tache cron spam
  cron: name="Update ban list nginx" minute="30" hour="0" job="/opt/tharyrok/stopforumspam/spam.sh"
  when: ansible_hostname in spam_nginx

- name: Activer le service nginx au démérage
  service: name={{ item }} state=restarted enabled=yes
  with_items:
    - munin-node
    - nginx
