---

- hosts: all
  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    DOMAIN: img.imotep-gaming.fr
    DIR: /var/www/img.imotep-gaming.fr/
    LE: true
    SSL_UNIQ: true
    SSL: true
    PROXY_PORT: 3000


  roles:
    - { role: 'user', when: ansible_hostname == 'web' }
    - { role: 'letsencrypt-apps', when: ansible_hostname == 'web' }
    - { role: 'nginx-apps', when: ansible_hostname == 'web' }

  tasks:
    - name: Installation camo
      git: repo=https://github.com/atmos/camo dest={{ DIR }}
      when: ansible_hostname == 'web'

    - name: Création fichier de configuration supervisor
      template: src={{ playbook_dir }}/../files/web/img.imotep-gaming.fr/img.imotep-gaming.fr.conf.j2 dest="/etc/supervisor/conf.d/{{ DOMAIN | replace(".", "-") }}.conf" owner=root group=root mode="u+rw,g+r,o+r"
      notify: restart supervisor
      when: ansible_hostname == 'web'
  
  handlers:
    - name: restart supervisor
      supervisorctl: name='{{ DOMAIN | replace(".", "-") }}' state=restarted