---

- hosts: all
  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    DOMAIN: imotep-gaming.fr
    DIR: /var/www/imotep-gaming.fr/
    LE: true
    SSL: true
    SSL_UNIQ: true
    TECHNO: php
    PROXY: false
    PROXY_SSL: false
    PROXY_IP: false


  roles:
    - { role: 'user', when: ansible_hostname == 'web' }
    - { role: 'letsencrypt-apps', when: ansible_hostname == 'web' }
    - { role: 'nginx-apps', when: ansible_hostname == 'web' }
    - { role: 'php5-apps', when: ansible_hostname == 'web' }
    - { role: 'proftpd-apps', when: ansible_hostname == 'sql' }
