---

- hosts: all
  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    DOMAIN: mail.tharyrok.eu.org
    DIR: /var/www/mail-tharyrok-eu-org/public_html
    LE: true
    SSL: true
    SSL_UNIQ: true
    TECHNO: php
    PROXY: false


  roles:
    - { role: 'user', when: ansible_hostname == 'web' }
    - { role: 'nginx-apps', when: ansible_hostname == 'web' }
    - { role: 'php7-apps', when: ansible_hostname == 'web' }
    - { role: 'letsencrypt-apps', when: ansible_hostname == 'web' }
    - { role: 'proftpd-apps', when: ansible_hostname == 'sql' }

  tasks:
    - name: create database mail
      mysql_db: name=mail-tharyrok state=present login_user=root login_password={{ MYSQL_ROOT }}
      when: ansible_hostname == 'sql'

    - name: create user mail mysql for lan
      mysql_user: name=mail-tharyrok password={{ MYSQL_MAIL_THARYROK }} priv=mail-tharyrok.*:ALL host={{ item }} state=present login_user=root login_password={{ MYSQL_ROOT }}
      with_items:
        - "127.0.0.1"
        - "localhost"
        - "192.168.70.%"
        - "sql.r2-d2.tharyrok.eu.org"
      when: ansible_hostname == 'sql'
