---

- hosts: all
  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    DOMAIN: sound.imotep-gaming.fr
    DIR: /var/www/sound.imotep-gaming.fr/
    NGINX_MODE: "vhost-ssl"
    TECHNO: php

  roles:
    - { role: 'user', when: ansible_hostname == 'web' }
    - { role: 'letsencrypt-apps', when: ansible_hostname == 'web' }
    - { role: 'nginx-apps', when: ansible_hostname == 'web' }
    - { role: 'php7-apps', when: ansible_hostname == 'web' }
    #- { role: 'proftpd-apps', when: ansible_hostname == 'sql' }

  tasks:
    - name: create database imotep-sound
      mysql_db: name=imotep-sound state=present login_user=root login_password={{ MYSQL_ROOT }}
      when: ansible_hostname == 'sql'

    - name: create user imotep-sound mysql for lan
      mysql_user: name=imotep-sound password={{ MYSQL_IMOTEP_SOUND }} priv=imotep-sound.*:ALL host={{ item }} state=present login_user=root login_password={{ MYSQL_ROOT }}
      with_items:
        - "127.0.0.1"
        - "localhost"
        - "192.168.70.%"
        - "sql.r2-d2.tharyrok.eu.org"
      when: ansible_hostname == 'sql'
