---

- hosts: all
  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    DOMAIN: torrent.tharyrok.eu.org
    DIR: /var/www/torrent.tharyrok.eu.org/
    TECHNO: php
    PROXY: "torrent.r2-d2.tharyrok.eu.org"
    NGINX_INCLUDE: "{{ playbook_dir }}/../files/web/torrent.tharyrok.eu.org/nginx.j2"

  roles:
    - { role: 'user', when: ansible_hostname == 'torrent' }
    - { role: 'letsencrypt-apps', when: ansible_hostname == 'web' }
    - { role: 'nginx-apps', when: ansible_hostname == 'web', NGINX_MODE: "proxy-ssl" }
    - { role: 'nginx-apps', when: ansible_hostname == 'torrent', NGINX_MODE: "vhost" }
    - { role: 'php7-apps', when: ansible_hostname == 'torrent' }

  tasks:
    - name: Installation ruTorrent
      git: repo=https://github.com/Novik/ruTorrent dest={{ DIR }}
      when: ansible_hostname == 'torrent'
