---

- name: restart monit
  service: name=monit state=restarted

- name: restart ssh
  service: name=ssh state=restarted

- name: restart munin-node
  service: name=munin-node state=restarted

- name: restart unbound
  service: name=unbound state=restarted

- name: restart sshguard
  service: name=sshguard state=restarted
