#!/bin/bash

load=$(cat /proc/loadavg | awk '{print $1" "$2" "$3}')
disk=$( df -h | grep ^\/dev\/ | awk '{print $6" "$5" " }' | sed ':a;N;$!ba;s/\n/ /g')
memory_usage=$(free -m | awk '/Mem:/ { total=$2 } /buffers\/cache/ { used=$3 } END { printf("%3.1f%%", (used/total)*100)}')
memory=$(free -t -m | grep "Mem" | awk '{print $2" MB";}')
memory_used=$(free -t -m | grep Total | awk '{print $3" MB";}')
swap_usage=$(free -m | awk '/Swap/ { printf("%3.1f%%", "exit !$2;$3/$2*100") }')
users=$( w -s | grep -v WHAT | grep -v "load average" | wc -l)
time=$(uptime | grep -ohe 'up .*' | sed 's/,/\ hours/g' | awk '{ printf $2" "$3 }')
processes_total=$(ps aux | wc -l)
ip4=$(ip -4 addr show | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | sed ':a;N;$!ba;s/\n/ /g')
hostname=$(hostname -f)

echo -e "\033[1;37m"
echo -e "\033[1;33m                 ___         "
echo -e "\033[1;33m             ,-'\"   \"\`-.      \033[1;31mHostname ..... \033[1;34m" $hostname
echo -e "\033[1;33m           ,'_          \`.    \033[1;31mIP4 .......... \033[1;34m" $ip4
echo -e "\033[1;33m          / / \\  ,-       \   \033[1;31mIP6 .......... \033[1;34m"
echo -e "\033[1;33m     __   | \\_0 ---        |  "
echo -e "\033[1;33m    /  |  |                |  \033[1;31mSystem load .. \033[1;34m" $load
echo -e "\033[1;33m    \\  \\  \`--.______,-/    |  \033[1;31mUptime ....... \033[1;34m" "$time"
echo -e "\033[1;33m  ___)  \\  ,--\"\"    ,/     |  "
echo -e "\033[1;33m /    _  \\ \\-_____,-      /   \033[1;31mMemory usage . \033[1;34m" $memory_used"/"$memory" ("$memory_usage")"
echo -e "\033[1;33m \\__-/ \\  | \`.          ,'    \033[1;31mSwap usage ... \033[1;34m" $swap_usage
echo -e "\033[1;33m   \\___/ <    '--------'     "
echo -e "\033[1;33m    \\__/\ |                   \033[1;31mDisk usage ... \033[1;34m" $disk
echo -e "\033[1;33m     \\__//                    \033[1;31mProcesses .... \033[1;34m" $processes_total
echo -e "\033[0m"