---

- hosts: azi-3.tharyrok.eu.org

  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    unbound_conf:
      interface:
        - "192.168.12.254"
        - "127.0.0.1"
        - "::1"
      access:
        - "192.168.12.0/24"
        - "127.0.0.1"
        - "::1"

  roles:
    - unbound
