---

- hosts: c-3po.tharyrok.eu.org

  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    unbound_conf:
      interface:
        - "127.0.0.1"
        - "::1"
      access:
        - "127.0.0.1"
        - "::1"
    iptables:
      TCP:
        - { port_dst: 22 }
        - { port_dst: 80 }
        - { port_dst: 443 }
        - { port_dst: 30033 }
        - { port_dst: 10011 }
        - { port_dst: 41144 }
        - { port_dst: 655 }
        - { port_dst: 25826, ip4_src: "192.168.42.0/24" }
        - { port_dst: 25826, ip4_src: "192.168.70.0/24" }
        - { port_dst: 6379, ip4_src: "192.168.70.0/24" }
        - { port_dst: 6379, ip4_src: "192.168.42.0/24" }

      UDP:
        - { port_dst: 655 }
        - { port_dst: 2011 }
        - { port_dst: 9987 }
        - { port_dst: 25826, ip4_src: "192.168.42.0/24" }
        - { port_dst: 25826, ip4_src: "192.168.70.0/24" }

  roles:
    - iptables
    - unbound
    - letsencrypt-infra
    - nginx-infra