---
# confgig commun de tout les hosts
# pour plus d'infos il faut regarder dans roles/*

- hosts: all

  pre_tasks:
    - include_vars: ../secured/password.yml
    - name: Update cache
      apt: update_cache=yes cache_valid_time=3600
 
  roles:
    - commun
