---

- hosts: dns.r2-d2.tharyrok.eu.org

  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    nsd:
      - assalyzo.eu.org
      - assalyzo.eu
      - blirala.eu.org
      - blirala.eu
      - lirarice.eu.org
      - lirarice.ovh
      - tharyrok.eu.org
      - tharyrok.eu
      - tmin.eu
      - mc.imotep-gaming.fr

  roles:
    - nsd
