---

- hosts: flo.tharyrok.eu.org

  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    unbound_conf:
      interface:
        - "127.0.0.1"
        - "::1"
      access:
        - "127.0.0.1"
        - "::1"
    iptables:
      TCP:
        - { port_dst: 22 }
        - { port_dst: 655 }
        - { port_dst: 25565 }


      UDP:
        - { port_dst: 655 }
        - { port_dst: 25565 }

  roles:
    - iptables
    - unbound