---

- hosts: r2-d2.tharyrok.eu.org

  pre_tasks:
    - include_vars: ../secured/password.yml
  vars:
    iptables:
      IPV4_FORWARD: true
      IP4_WAN: "62.210.100.21"
      FORWARD_4:
        - {iface_src: "br-lan", iface_dst: "eth0"}

      TCP:
        - { port_dst: 22 }
        - { port_dst: 655 }
        - { port_dst: 53, ip4_src: "192.168.70.0/24"}

      UDP:
        - { port_dst: 655 }
        - { port_dst: 53, ip4_src: "192.168.70.0/24"}

      TCP_FORWARD:
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "108.61.224.67"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "173.244.206.25"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "173.244.206.26"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "88.198.106.11"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "78.46.95.154"}

       - { port_dst: 25, ip4_dst: "192.168.70.10"}
       - { port_dst: 587, ip4_dst: "192.168.70.10"}
       - { port_dst: 465, ip4_dst: "192.168.70.10"}
       - { port_dst: 143, ip4_dst: "192.168.70.10"}
       - { port_dst: 993, ip4_dst: "192.168.70.10"}
       - { port_dst: 4190, ip4_dst: "192.168.70.10"}

       - { port_dst: 80, ip4_dst: "192.168.70.20"}
       - { port_dst: 443, ip4_dst: "192.168.70.20"}
       - { port_dst: 2222, ip4_dst: "192.168.70.20"}

       - { port_dst: 25565, ip4_dst: "192.168.70.25"}
       - { port_dst: 25512, ip4_dst: "192.168.70.25"}

       - { port_dst: 32400, ip4_dst: "192.168.70.30"}
       - { port_dst: 4949, ip4_dst: "192.168.70.30"}

       - { port_dst: 51413, ip4_dst: "192.168.70.35"}
       - { port_dst: 3000, ip4_dst: "192.168.70.35"}
       - { port_dst: 137, ip4_dst: "192.168.70.35"}
       - { port_dst: 138, ip4_dst: "192.168.70.35"}
       - { port_dst: 139, ip4_dst: "192.168.70.35"}
       - { port_dst: 445, ip4_dst: "192.168.70.35"}

       - { port_dst: 5222, ip4_dst: "192.168.70.45"}
       - { port_dst: 5322, ip4_dst: "192.168.70.45"}
       - { port_dst: 4949, ip4_dst: "192.168.70.45"}


      UDP_FORWARD:
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "108.61.224.67"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "173.244.206.25"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "173.244.206.26"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "88.198.106.11"}
       - { port_dst: 53, ip4_dst: "192.168.70.5", ip4_src: "78.46.95.154"}

       - { port_dst: 25565, ip4_dst: "192.168.70.25"}
       - { port_dst: 25512, ip4_dst: "192.168.70.25"}

       - { port_dst: 32400, ip4_dst: "192.168.70.30"}

       - { port_dst: 51413, ip4_dst: "192.168.70.35"}

       - { port_dst: 5222, ip4_dst: "192.168.70.45"}
       - { port_dst: 5322, ip4_dst: "192.168.70.45"}

      MASQUERADE:
       - { iface_dst: "eth0", ip4_src: "192.168.70.0/24"}

  roles:
    - iptables
    - unbound
