---

- name: Installation de openssl, python, busybox
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - openssl
    - python

- name: Ajout de l'user
  user: name=letsencrypt shell=/bin/false append=yes state=present uid=999

- name: Créer repertoire letsencrypt
  file: path=/home/letsencrypt/{{ item }} state=directory owner=letsencrypt group=letsencrypt mode="u+rwX,g+rwX,o+r" recurse=yes
  with_items:
    - bundles
    - ssl
    - webroot

- name: Copie des fichier acme_tiny
  copy: src=le-cron.sh dest=/home/letsencrypt/le-cron.sh owner=letsencrypt group=letsencrypt mode="u+rx,g-rwx,o-rwx"

- name: téléchargement plugin munin
  get_url: url=https://raw.githubusercontent.com/diafygi/acme-tiny/master/acme_tiny.py dest=/home/letsencrypt/acme_tiny.py owner=letsencrypt group=letsencrypt mode="u+rx,g-rwx,o-rwx" force=yes

- name: Copie des fichier letsencrypt.key
  copy: src=../secured/ssl/letsencrypt.key dest=/home/letsencrypt/ssl/letsencrypt.key owner=letsencrypt group=letsencrypt mode="u+r,g-rwx,o-rwx"

- name: Copie des fichier dh4096.pem
  copy: src=../secured/ssl/dh4096.pem dest=/home/letsencrypt/ssl/dh4096.pem owner=letsencrypt group=letsencrypt mode="u+r,g+r,o+r"

- name: cron letsencrypt
  cron: name="check certificates" minute="30" hour="4" user="letsencrypt" job="/home/letsencrypt/le-cron.sh"

